// SkillGraph Neo4j Ingestion Cypher Script
// Creates unique constraints
CREATE CONSTRAINT IF NOT EXISTS FOR (e:Employee) REQUIRE e.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (s:Skill) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (r:Role) REQUIRE r.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (c:Course) REQUIRE c.id IS UNIQUE;

MERGE (:Skill {id: 'SKILL_SKL-001', name: 'Python'});
MERGE (:Skill {id: 'SKILL_SKL-002', name: 'Java'});
MERGE (:Skill {id: 'SKILL_SKL-003', name: 'JavaScript'});
MERGE (:Skill {id: 'SKILL_SKL-004', name: 'C++'});
MERGE (:Skill {id: 'SKILL_SKL-005', name: 'C#'});
MERGE (:Skill {id: 'SKILL_SKL-006', name: 'Ruby'});
MERGE (:Skill {id: 'SKILL_SKL-007', name: 'PHP'});
MERGE (:Skill {id: 'SKILL_SKL-008', name: 'Go'});
MERGE (:Skill {id: 'SKILL_SKL-009', name: 'Rust'});
MERGE (:Skill {id: 'SKILL_SKL-010', name: 'TypeScript'});
MERGE (:Skill {id: 'SKILL_SKL-011', name: 'Kotlin'});
MERGE (:Skill {id: 'SKILL_SKL-012', name: 'Swift'});
MERGE (:Skill {id: 'SKILL_SKL-013', name: 'Scala'});
MERGE (:Skill {id: 'SKILL_SKL-014', name: 'Perl'});
MERGE (:Skill {id: 'SKILL_SKL-015', name: 'Bash/Shell'});
MERGE (:Skill {id: 'SKILL_SKL-016', name: 'R'});
MERGE (:Skill {id: 'SKILL_SKL-017', name: 'HTML/CSS'});
MERGE (:Skill {id: 'SKILL_SKL-018', name: 'React'});
MERGE (:Skill {id: 'SKILL_SKL-019', name: 'Vue.js'});
MERGE (:Skill {id: 'SKILL_SKL-020', name: 'Angular'});
MERGE (:Skill {id: 'SKILL_SKL-021', name: 'Node.js'});
MERGE (:Skill {id: 'SKILL_SKL-022', name: 'Django'});
MERGE (:Skill {id: 'SKILL_SKL-023', name: 'Flask'});
MERGE (:Skill {id: 'SKILL_SKL-024', name: 'REST APIs'});
MERGE (:Skill {id: 'SKILL_SKL-025', name: 'GraphQL'});
MERGE (:Skill {id: 'SKILL_SKL-026', name: 'Responsive Design'});
MERGE (:Skill {id: 'SKILL_SKL-027', name: 'Web Accessibility'});
MERGE (:Skill {id: 'SKILL_SKL-028', name: 'Seo'});
MERGE (:Skill {id: 'SKILL_SKL-029', name: 'Android'});
MERGE (:Skill {id: 'SKILL_SKL-030', name: 'Ios'});
MERGE (:Skill {id: 'SKILL_SKL-031', name: 'React Native'});
MERGE (:Skill {id: 'SKILL_SKL-032', name: 'Flutter'});
MERGE (:Skill {id: 'SKILL_SKL-033', name: 'Mobile Ui/Ux'});
MERGE (:Skill {id: 'SKILL_SKL-034', name: 'Mobile Security'});
MERGE (:Skill {id: 'SKILL_SKL-035', name: 'App Testing'});
MERGE (:Skill {id: 'SKILL_SKL-036', name: 'AWS'});
MERGE (:Skill {id: 'SKILL_SKL-037', name: 'Azure'});
MERGE (:Skill {id: 'SKILL_SKL-038', name: 'GCP'});
MERGE (:Skill {id: 'SKILL_SKL-039', name: 'Docker'});
MERGE (:Skill {id: 'SKILL_SKL-040', name: 'Kubernetes'});
MERGE (:Skill {id: 'SKILL_SKL-041', name: 'CI/CD'});
MERGE (:Skill {id: 'SKILL_SKL-042', name: 'Jenkins'});
MERGE (:Skill {id: 'SKILL_SKL-043', name: 'Terraform'});
MERGE (:Skill {id: 'SKILL_SKL-044', name: 'Cloudformation'});
MERGE (:Skill {id: 'SKILL_SKL-045', name: 'Ansible'});
MERGE (:Skill {id: 'SKILL_SKL-046', name: 'Microservices'});
MERGE (:Skill {id: 'SKILL_SKL-047', name: 'Serverless'});
MERGE (:Skill {id: 'SKILL_SKL-048', name: 'Machine Learning'});
MERGE (:Skill {id: 'SKILL_SKL-049', name: 'Deep Learning'});
MERGE (:Skill {id: 'SKILL_SKL-050', name: 'TensorFlow'});
MERGE (:Skill {id: 'SKILL_SKL-051', name: 'PyTorch'});
MERGE (:Skill {id: 'SKILL_SKL-052', name: 'Scikit-Learn'});
MERGE (:Skill {id: 'SKILL_SKL-053', name: 'Data Analysis'});
MERGE (:Skill {id: 'SKILL_SKL-054', name: 'Statistics'});
MERGE (:Skill {id: 'SKILL_SKL-055', name: 'Pandas'});
MERGE (:Skill {id: 'SKILL_SKL-056', name: 'NumPy'});
MERGE (:Skill {id: 'SKILL_SKL-057', name: 'SQL'});
MERGE (:Skill {id: 'SKILL_SKL-058', name: 'Tableau'});
MERGE (:Skill {id: 'SKILL_SKL-059', name: 'Power BI'});
MERGE (:Skill {id: 'SKILL_SKL-060', name: 'Jupyter'});
MERGE (:Skill {id: 'SKILL_SKL-061', name: 'MySQL'});
MERGE (:Skill {id: 'SKILL_SKL-062', name: 'PostgreSQL'});
MERGE (:Skill {id: 'SKILL_SKL-063', name: 'MongoDB'});
MERGE (:Skill {id: 'SKILL_SKL-064', name: 'Oracle'});
MERGE (:Skill {id: 'SKILL_SKL-065', name: 'Cassandra'});
MERGE (:Skill {id: 'SKILL_SKL-066', name: 'Redis'});
MERGE (:Skill {id: 'SKILL_SKL-067', name: 'Database Design'});
MERGE (:Skill {id: 'SKILL_SKL-068', name: 'Query Optimization'});
MERGE (:Skill {id: 'SKILL_SKL-069', name: 'Nosql'});
MERGE (:Skill {id: 'SKILL_SKL-070', name: 'Leadership'});
MERGE (:Skill {id: 'SKILL_SKL-071', name: 'Communication'});
MERGE (:Skill {id: 'SKILL_SKL-072', name: 'Problem Solving'});
MERGE (:Skill {id: 'SKILL_SKL-073', name: 'Critical Thinking'});
MERGE (:Skill {id: 'SKILL_SKL-074', name: 'Teamwork'});
MERGE (:Skill {id: 'SKILL_SKL-075', name: 'Time Management'});
MERGE (:Skill {id: 'SKILL_SKL-076', name: 'Adaptability'});
MERGE (:Skill {id: 'SKILL_SKL-077', name: 'Creativity'});
MERGE (:Skill {id: 'SKILL_SKL-078', name: 'Negotiation'});
MERGE (:Skill {id: 'SKILL_SKL-079', name: 'Mentoring'});
MERGE (:Skill {id: 'SKILL_SKL-080', name: 'Project Management'});
MERGE (:Skill {id: 'SKILL_SKL-081', name: 'Strategic Planning'});
MERGE (:Skill {id: 'SKILL_SKL-082', name: 'Decision Making'});
MERGE (:Skill {id: 'SKILL_SKL-083', name: 'Financial Analysis'});
MERGE (:Skill {id: 'SKILL_SKL-084', name: 'Business Development'});
MERGE (:Skill {id: 'SKILL_SKL-085', name: 'Market Research'});
MERGE (:Skill {id: 'SKILL_SKL-086', name: 'Business Acumen'});
MERGE (:Skill {id: 'SKILL_SKL-087', name: 'Sales'});
MERGE (:Skill {id: 'SKILL_SKL-088', name: 'Marketing'});
MERGE (:Skill {id: 'SKILL_SKL-089', name: 'Budget Management'});
MERGE (:Skill {id: 'SKILL_SKL-090', name: 'P&L Management'});
MERGE (:Skill {id: 'SKILL_SKL-091', name: 'User Experience'});
MERGE (:Skill {id: 'SKILL_SKL-092', name: 'User Interface'});
MERGE (:Skill {id: 'SKILL_SKL-093', name: 'Graphic Design'});
MERGE (:Skill {id: 'SKILL_SKL-094', name: 'Web Design'});
MERGE (:Skill {id: 'SKILL_SKL-095', name: 'Adobe Creative Suite'});
MERGE (:Skill {id: 'SKILL_SKL-096', name: 'Figma'});
MERGE (:Skill {id: 'SKILL_SKL-097', name: 'Wireframing'});
MERGE (:Skill {id: 'SKILL_SKL-098', name: 'Prototyping'});
MERGE (:Skill {id: 'SKILL_SKL-099', name: 'Penetration Testing'});
MERGE (:Skill {id: 'SKILL_SKL-100', name: 'Network Security'});
MERGE (:Skill {id: 'SKILL_SKL-101', name: 'Encryption'});
MERGE (:Skill {id: 'SKILL_SKL-102', name: 'Firewalls'});
MERGE (:Skill {id: 'SKILL_SKL-103', name: 'Security Protocols'});
MERGE (:Skill {id: 'SKILL_SKL-104', name: 'Risk Assessment'});
MERGE (:Skill {id: 'SKILL_SKL-105', name: 'Compliance'});
MERGE (:Skill {id: 'SKILL_SKL-106', name: 'Security Architecture'});
MERGE (:Skill {id: 'SKILL_SKL-107', name: 'Agile Methodologies'});
MERGE (:Skill {id: 'SKILL_SKL-108', name: 'Kanban'});
MERGE (:Skill {id: 'SKILL_SKL-109', name: 'Jira'});
MERGE (:Skill {id: 'SKILL_SKL-110', name: 'Confluence'});
MERGE (:Skill {id: 'SKILL_SKL-111', name: 'Documentation'});
MERGE (:Skill {id: 'SKILL_SKL-112', name: 'Technical Writing'});
MERGE (:Skill {id: 'SKILL_SKL-113', name: 'Presentation Skills'});
MERGE (:Skill {id: 'SKILL_SKL-114', name: 'FastAPI'});
MERGE (:Skill {id: 'SKILL_SKL-115', name: 'Linux'});
MERGE (:Skill {id: 'SKILL_SKL-116', name: 'Git'});
MERGE (:Skill {id: 'SKILL_SKL-117', name: 'Natural Language Processing'});
MERGE (:Skill {id: 'SKILL_SKL-118', name: 'Cybersecurity'});
MERGE (:Skill {id: 'SKILL_SKL-119', name: 'System Design'});
MERGE (:Role {id: 'ROLE_ROL-001', name: 'Software Engineer'});
MERGE (:Role {id: 'ROLE_ROL-002', name: 'Full Stack Developer'});
MERGE (:Role {id: 'ROLE_ROL-003', name: 'Frontend Developer'});
MERGE (:Role {id: 'ROLE_ROL-004', name: 'Backend Developer'});
MERGE (:Role {id: 'ROLE_ROL-005', name: 'DevOps Engineer'});
MERGE (:Role {id: 'ROLE_ROL-006', name: 'Cloud Architect'});
MERGE (:Role {id: 'ROLE_ROL-007', name: 'Data Scientist'});
MERGE (:Role {id: 'ROLE_ROL-008', name: 'Machine Learning Engineer'});
MERGE (:Role {id: 'ROLE_ROL-009', name: 'Database Administrator'});
MERGE (:Role {id: 'ROLE_ROL-010', name: 'Cybersecurity Specialist'});
MERGE (:Role {id: 'ROLE_ROL-011', name: 'Security Engineer'});
MERGE (:Role {id: 'ROLE_ROL-012', name: 'Mobile Developer Android'});
MERGE (:Role {id: 'ROLE_ROL-013', name: 'Software Architect'});
MERGE (:Role {id: 'ROLE_ROL-014', name: 'Technical Lead'});
MERGE (:Role {id: 'ROLE_ROL-015', name: 'Data Analyst'});
MERGE (:Role {id: 'ROLE_ROL-016', name: 'BI Developer'});
MERGE (:Role {id: 'ROLE_ROL-017', name: 'BI Analyst'});
MERGE (:Role {id: 'ROLE_ROL-018', name: 'Audit Manager'});
MERGE (:Role {id: 'ROLE_ROL-019', name: 'HR Manager'});
MERGE (:Role {id: 'ROLE_ROL-020', name: 'HR Business Partner'});
MERGE (:Role {id: 'ROLE_ROL-021', name: 'HR Operations Manager'});
MERGE (:Role {id: 'ROLE_ROL-022', name: 'Marketing Manager'});
MERGE (:Role {id: 'ROLE_ROL-023', name: 'Product Manager'});
MERGE (:Role {id: 'ROLE_ROL-024', name: 'Business Development Manager'});
MERGE (:Role {id: 'ROLE_ROL-025', name: 'Operations Manager'});
MERGE (:Role {id: 'ROLE_ROL-026', name: 'Quality Assurance Manager'});
MERGE (:Role {id: 'ROLE_ROL-027', name: 'Project Engineer'});
MERGE (:Role {id: 'ROLE_ROL-028', name: 'Real Estate Agent'});
MERGE (:Role {id: 'ROLE_ROL-029', name: 'Real Estate Broker'});
MERGE (:Role {id: 'ROLE_ROL-030', name: 'Healthcare Administrator'});
MERGE (:Role {id: 'ROLE_ROL-031', name: 'UX Designer'});
MERGE (:Role {id: 'ROLE_ROL-032', name: 'Web Designer'});
MERGE (:Role {id: 'ROLE_ROL-033', name: 'Producer'});
MERGE (:Role {id: 'ROLE_ROL-034', name: 'Director'});
MERGE (:Role {id: 'ROLE_ROL-035', name: 'Judge'});
MERGE (:Role {id: 'ROLE_ROL-036', name: 'Management Consultant'});
MERGE (:Role {id: 'ROLE_ROL-037', name: 'Strategy Consultant'});
MERGE (:Role {id: 'ROLE_ROL-038', name: 'Business Consultant'});
MERGE (:Role {id: 'ROLE_ROL-039', name: 'IT Consultant'});
MERGE (:Role {id: 'ROLE_ROL-040', name: 'Call Center Manager'});
MERGE (:Role {id: 'ROLE_ROL-041', name: 'Product Researcher'});
MERGE (:Role {id: 'ROLE_ROL-042', name: 'Office Manager'});
MERGE (:Role {id: 'ROLE_ROL-043', name: 'Chief Executive Officer'});
MERGE (:Role {id: 'ROLE_ROL-044', name: 'COO'});
MERGE (:Role {id: 'ROLE_ROL-045', name: 'Vice President'});
MERGE (:Role {id: 'ROLE_ROL-046', name: 'General Manager'});
MERGE (:Role {id: 'ROLE_ROL-047', name: 'Public Administrator'});
MERGE (:Role {id: 'ROLE_ROL-048', name: 'Safety Engineer'});
MERGE (:Role {id: 'ROLE_ROL-049', name: 'Event Coordinator'});
MERGE (:Role {id: 'ROLE_ROL-050', name: 'Sports Manager'});
MERGE (:Role {id: 'ROLE_ROL-051', name: 'Fitness Manager'});
MERGE (:Role {id: 'ROLE_ROL-052', name: 'Non-profit Director'});
MERGE (:Role {id: 'ROLE_ROL-053', name: 'Fundraiser'});
MERGE (:Role {id: 'ROLE_ROL-054', name: 'Sustainability Consultant'});
MERGE (:Role {id: 'ROLE_ROL-055', name: 'AI/ML Specialist'});
MERGE (:Role {id: 'ROLE_ROL-056', name: 'DevSecOps Engineer'});
MERGE (:Role {id: 'ROLE_ROL-057', name: 'Solution Architect'});
MERGE (:Role {id: 'ROLE_ROL-058', name: 'React Developer'});
MERGE (:Role {id: 'ROLE_ROL-059', name: 'Vue Developer'});
MERGE (:Role {id: 'ROLE_ROL-060', name: 'Angular Developer'});
MERGE (:Role {id: 'ROLE_ROL-061', name: 'PHP Developer'});
MERGE (:Role {id: 'ROLE_ROL-062', name: 'Python Developer'});
MERGE (:Role {id: 'ROLE_ROL-063', name: 'Ruby Developer'});
MERGE (:Role {id: 'ROLE_ROL-064', name: 'Go Developer'});
MERGE (:Role {id: 'ROLE_ROL-065', name: 'Java Backend Developer'});
MERGE (:Role {id: 'ROLE_ROL-066', name: 'C# Developer'});
MERGE (:Role {id: 'ROLE_ROL-067', name: 'Scala Developer'});
MERGE (:Role {id: 'ROLE_ROL-068', name: 'Shell Script Developer'});
MERGE (:Role {id: 'ROLE_ROL-069', name: 'TypeScript Developer'});
MERGE (:Role {id: 'ROLE_ROL-070', name: 'Jupyter Developer'});
MERGE (:Role {id: 'ROLE_ROL-071', name: 'MongoDB Developer'});
MERGE (:Role {id: 'ROLE_ROL-072', name: 'Spark Developer'});
MERGE (:Role {id: 'ROLE_ROL-073', name: 'Tableau Specialist'});
MERGE (:Role {id: 'ROLE_ROL-074', name: 'WordPress Developer'});
MERGE (:Role {id: 'ROLE_ROL-075', name: 'Drupal Developer'});
MERGE (:Role {id: 'ROLE_ROL-076', name: 'Magento Developer'});
MERGE (:Role {id: 'ROLE_ROL-077', name: 'Joomla Developer'});
MERGE (:Role {id: 'ROLE_ROL-078', name: 'Privacy Officer'});
MERGE (:Role {id: 'ROLE_ROL-079', name: 'Compliance Officer'});
MERGE (:Role {id: 'ROLE_ROL-080', name: 'Technical Writer'});
MERGE (:Role {id: 'ROLE_ROL-081', name: 'Release Manager'});
MERGE (:Role {id: 'ROLE_ROL-082', name: 'IT Project Manager'});
MERGE (:Role {id: 'ROLE_ROL-083', name: 'Scrum Master'});
MERGE (:Role {id: 'ROLE_ROL-084', name: 'Product Owner'});
MERGE (:Role {id: 'ROLE_ROL-085', name: 'Academic Data Analyst'});
MERGE (:Role {id: 'ROLE_ROL-086', name: 'Loss Prevention Manager'});
MERGE (:Role {id: 'ROLE_ROL-087', name: 'Sales Associate'});
MERGE (:Role {id: 'ROLE_ROL-088', name: 'Server'});
MERGE (:Role {id: 'ROLE_ROL-089', name: 'Wildlife Biologist'});
MERGE (:Role {id: 'ROLE_ROL-090', name: 'Military Officer'});
MERGE (:Role {id: 'ROLE_ROL-091', name: 'Meteorologist'});
MERGE (:Role {id: 'ROLE_ROL-092', name: 'Botanist'});
MERGE (:Role {id: 'ROLE_ROL-093', name: 'Sports Agent'});
MERGE (:Role {id: 'ROLE_ROL-094', name: 'Exhibition Designer'});
MERGE (:Role {id: 'ROLE_ROL-095', name: 'Cloud Engineer'});
MERGE (:Role {id: 'ROLE_ROL-096', name: 'Security Analyst'});
MERGE (:Course {id: 'COURSE_CRS-001', name: 'Python Programming Foundations'});
MERGE (:Course {id: 'COURSE_CRS-002', name: 'Modern JavaScript & TypeScript Mastery'});
MERGE (:Course {id: 'COURSE_CRS-003', name: 'Linux System Administration & Shell Scripting'});
MERGE (:Course {id: 'COURSE_CRS-004', name: 'Relational Databases & SQL Optimization'});
MERGE (:Course {id: 'COURSE_CRS-005', name: 'Computer Networking & Web Protocols'});
MERGE (:Course {id: 'COURSE_CRS-006', name: 'Cloud Computing Foundations with AWS'});
MERGE (:Course {id: 'COURSE_CRS-007', name: 'Docker Containers & Microservices Essentials'});
MERGE (:Course {id: 'COURSE_CRS-008', name: 'Kubernetes Container Orchestration at Scale'});
MERGE (:Course {id: 'COURSE_CRS-009', name: 'CI/CD Automation & Infrastructure as Code (Terraform)'});
MERGE (:Course {id: 'COURSE_CRS-010', name: 'Modern Frontend Development with React'});
MERGE (:Course {id: 'COURSE_CRS-011', name: 'Backend Engineering with FastAPI & Microservices'});
MERGE (:Course {id: 'COURSE_CRS-012', name: 'Applied Data Analysis with Pandas & NumPy'});
MERGE (:Course {id: 'COURSE_CRS-013', name: 'Machine Learning Algorithms with Scikit-Learn'});
MERGE (:Course {id: 'COURSE_CRS-014', name: 'Deep Learning & NLP with PyTorch'});
MERGE (:Course {id: 'COURSE_CRS-015', name: 'Production MLOps & Model Deployment'});
MERGE (:Course {id: 'COURSE_CRS-016', name: 'Enterprise Cybersecurity & Network Defense'});
MERGE (:Course {id: 'COURSE_CRS-017', name: 'System Design & Distributed Architecture'});
MERGE (:Course {id: 'COURSE_CRS-018', name: 'Agile Leadership & Cross-Functional Teamwork'});
MERGE (:Employee {id: 'EMP_EMP-001', name: 'Alex Rivera'});
MERGE (:Employee {id: 'EMP_EMP-002', name: 'Priya Sharma'});
MERGE (:Employee {id: 'EMP_EMP-003', name: 'Marcus Chen'});
MERGE (:Employee {id: 'EMP_EMP-004', name: 'Elena Rostova'});
MERGE (:Employee {id: 'EMP_EMP-005', name: 'David Kim'});
MERGE (:Employee {id: 'EMP_EMP-006', name: 'Sarah Jenkins (HR Admin)'});

// Relationships
MATCH (a {id: 'ROLE_ROL-001'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-001'}), (b {id: 'SKILL_SKL-002'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-001'}), (b {id: 'SKILL_SKL-004'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-001'}), (b {id: 'SKILL_SKL-116'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-001'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-002'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-002'}), (b {id: 'SKILL_SKL-010'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-002'}), (b {id: 'SKILL_SKL-018'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-002'}), (b {id: 'SKILL_SKL-021'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-002'}), (b {id: 'SKILL_SKL-114'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-002'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-002'}), (b {id: 'SKILL_SKL-116'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-002'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-003'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-003'}), (b {id: 'SKILL_SKL-010'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-003'}), (b {id: 'SKILL_SKL-018'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-003'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-003'}), (b {id: 'SKILL_SKL-116'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-004'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-004'}), (b {id: 'SKILL_SKL-114'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-004'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-004'}), (b {id: 'SKILL_SKL-062'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-004'}), (b {id: 'SKILL_SKL-039'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-004'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-004'}), (b {id: 'SKILL_SKL-116'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-005'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-005'}), (b {id: 'SKILL_SKL-039'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-005'}), (b {id: 'SKILL_SKL-040'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-005'}), (b {id: 'SKILL_SKL-041'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-005'}), (b {id: 'SKILL_SKL-036'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-005'}), (b {id: 'SKILL_SKL-116'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-005'}), (b {id: 'SKILL_SKL-015'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-006'}), (b {id: 'SKILL_SKL-036'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-006'}), (b {id: 'SKILL_SKL-037'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-006'}), (b {id: 'SKILL_SKL-038'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-006'}), (b {id: 'SKILL_SKL-119'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-007'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-007'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-007'}), (b {id: 'SKILL_SKL-055'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-007'}), (b {id: 'SKILL_SKL-052'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-007'}), (b {id: 'SKILL_SKL-048'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-007'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-008'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-008'}), (b {id: 'SKILL_SKL-048'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-008'}), (b {id: 'SKILL_SKL-049'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-008'}), (b {id: 'SKILL_SKL-051'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-008'}), (b {id: 'SKILL_SKL-039'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-008'}), (b {id: 'SKILL_SKL-114'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-009'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-009'}), (b {id: 'SKILL_SKL-063'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-009'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-010'}), (b {id: 'SKILL_SKL-099'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-010'}), (b {id: 'SKILL_SKL-103'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-010'}), (b {id: 'SKILL_SKL-101'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-010'}), (b {id: 'SKILL_SKL-102'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-011'}), (b {id: 'SKILL_SKL-106'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-011'}), (b {id: 'SKILL_SKL-101'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-011'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-011'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-012'}), (b {id: 'SKILL_SKL-002'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-012'}), (b {id: 'SKILL_SKL-011'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-012'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-013'}), (b {id: 'SKILL_SKL-119'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-013'}), (b {id: 'SKILL_SKL-046'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-013'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-014'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-014'}), (b {id: 'SKILL_SKL-079'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-014'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-014'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-015'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-015'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-015'}), (b {id: 'SKILL_SKL-058'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-016'}), (b {id: 'SKILL_SKL-059'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-016'}), (b {id: 'SKILL_SKL-058'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-016'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-016'}), (b {id: 'SKILL_SKL-067'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-017'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-017'}), (b {id: 'SKILL_SKL-058'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-017'}), (b {id: 'SKILL_SKL-059'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-017'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-018'}), (b {id: 'SKILL_SKL-104'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-018'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-018'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-018'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-019'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-019'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-019'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-020'}), (b {id: 'SKILL_SKL-086'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-020'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-020'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-021'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-021'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-021'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-021'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-022'}), (b {id: 'SKILL_SKL-089'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-022'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-022'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-023'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-023'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-023'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-024'}), (b {id: 'SKILL_SKL-087'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-024'}), (b {id: 'SKILL_SKL-078'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-024'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-025'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-025'}), (b {id: 'SKILL_SKL-080'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-025'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-026'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-026'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-026'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-027'}), (b {id: 'SKILL_SKL-080'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-027'}), (b {id: 'SKILL_SKL-111'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-027'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-027'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-028'}), (b {id: 'SKILL_SKL-087'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-028'}), (b {id: 'SKILL_SKL-088'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-028'}), (b {id: 'SKILL_SKL-078'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-028'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-029'}), (b {id: 'SKILL_SKL-078'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-029'}), (b {id: 'SKILL_SKL-084'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-029'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-030'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-030'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-030'}), (b {id: 'SKILL_SKL-081'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-030'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-031'}), (b {id: 'SKILL_SKL-097'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-031'}), (b {id: 'SKILL_SKL-098'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-031'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-032'}), (b {id: 'SKILL_SKL-094'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-032'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-032'}), (b {id: 'SKILL_SKL-091'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-032'}), (b {id: 'SKILL_SKL-026'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-032'}), (b {id: 'SKILL_SKL-077'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-033'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-033'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-033'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-033'}), (b {id: 'SKILL_SKL-077'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-034'}), (b {id: 'SKILL_SKL-081'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-034'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-034'}), (b {id: 'SKILL_SKL-082'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-034'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-035'}), (b {id: 'SKILL_SKL-082'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-035'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-035'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-036'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-036'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-036'}), (b {id: 'SKILL_SKL-080'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-037'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-037'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-037'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-038'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-038'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-038'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-038'}), (b {id: 'SKILL_SKL-080'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-039'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-039'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-039'}), (b {id: 'SKILL_SKL-119'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-039'}), (b {id: 'SKILL_SKL-080'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-040'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-040'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-040'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-041'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-041'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-041'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-042'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-042'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-042'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-043'}), (b {id: 'SKILL_SKL-082'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-043'}), (b {id: 'SKILL_SKL-086'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-043'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-044'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-044'}), (b {id: 'SKILL_SKL-082'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-044'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-045'}), (b {id: 'SKILL_SKL-084'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-045'}), (b {id: 'SKILL_SKL-082'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-045'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-046'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-046'}), (b {id: 'SKILL_SKL-081'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-046'}), (b {id: 'SKILL_SKL-082'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-046'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-047'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-047'}), (b {id: 'SKILL_SKL-089'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-047'}), (b {id: 'SKILL_SKL-081'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-047'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-048'}), (b {id: 'SKILL_SKL-104'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-048'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-048'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-048'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-049'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-049'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-049'}), (b {id: 'SKILL_SKL-089'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-050'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-050'}), (b {id: 'SKILL_SKL-088'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-050'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-050'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-051'}), (b {id: 'SKILL_SKL-087'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-051'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-051'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-052'}), (b {id: 'SKILL_SKL-081'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-052'}), (b {id: 'SKILL_SKL-089'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-052'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-053'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-053'}), (b {id: 'SKILL_SKL-087'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-053'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-054'}), (b {id: 'SKILL_SKL-086'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-054'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-054'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-055'}), (b {id: 'SKILL_SKL-049'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-055'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-055'}), (b {id: 'SKILL_SKL-050'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-055'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-056'}), (b {id: 'SKILL_SKL-041'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-056'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-056'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-057'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-057'}), (b {id: 'SKILL_SKL-086'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-057'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-058'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-058'}), (b {id: 'SKILL_SKL-018'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-058'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-059'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-059'}), (b {id: 'SKILL_SKL-019'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-059'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-060'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-060'}), (b {id: 'SKILL_SKL-020'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-060'}), (b {id: 'SKILL_SKL-010'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-060'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-061'}), (b {id: 'SKILL_SKL-007'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-061'}), (b {id: 'SKILL_SKL-061'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-061'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-062'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-062'}), (b {id: 'SKILL_SKL-022'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-062'}), (b {id: 'SKILL_SKL-023'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-062'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-062'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-062'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-063'}), (b {id: 'SKILL_SKL-006'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-063'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-063'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-063'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-064'}), (b {id: 'SKILL_SKL-008'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-064'}), (b {id: 'SKILL_SKL-046'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-064'}), (b {id: 'SKILL_SKL-039'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-064'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-065'}), (b {id: 'SKILL_SKL-002'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-065'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-065'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-065'}), (b {id: 'SKILL_SKL-046'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-066'}), (b {id: 'SKILL_SKL-005'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-066'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-066'}), (b {id: 'SKILL_SKL-037'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-067'}), (b {id: 'SKILL_SKL-013'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-067'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-067'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-068'}), (b {id: 'SKILL_SKL-015'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-068'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-068'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-069'}), (b {id: 'SKILL_SKL-010'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-069'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-069'}), (b {id: 'SKILL_SKL-021'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-069'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-070'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-070'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-070'}), (b {id: 'SKILL_SKL-111'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-071'}), (b {id: 'SKILL_SKL-063'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-071'}), (b {id: 'SKILL_SKL-069'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-071'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-072'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-072'}), (b {id: 'SKILL_SKL-013'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-072'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-073'}), (b {id: 'SKILL_SKL-058'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-073'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-073'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-074'}), (b {id: 'SKILL_SKL-007'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-074'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-074'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-075'}), (b {id: 'SKILL_SKL-007'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-075'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-075'}), (b {id: 'SKILL_SKL-061'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-076'}), (b {id: 'SKILL_SKL-007'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-076'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-076'}), (b {id: 'SKILL_SKL-061'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-076'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-077'}), (b {id: 'SKILL_SKL-007'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-077'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-077'}), (b {id: 'SKILL_SKL-061'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-078'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-078'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-078'}), (b {id: 'SKILL_SKL-081'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-079'}), (b {id: 'SKILL_SKL-105'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-079'}), (b {id: 'SKILL_SKL-111'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-079'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-080'}), (b {id: 'SKILL_SKL-112'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-080'}), (b {id: 'SKILL_SKL-111'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-080'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-080'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-081'}), (b {id: 'SKILL_SKL-080'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-081'}), (b {id: 'SKILL_SKL-111'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-081'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-081'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-082'}), (b {id: 'SKILL_SKL-080'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-082'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-082'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-082'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-083'}), (b {id: 'SKILL_SKL-107'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-083'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-083'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-084'}), (b {id: 'SKILL_SKL-107'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-084'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-084'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-084'}), (b {id: 'SKILL_SKL-086'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-085'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-085'}), (b {id: 'SKILL_SKL-016'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-085'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-086'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-086'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-086'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-087'}), (b {id: 'SKILL_SKL-087'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-087'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-087'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-087'}), (b {id: 'SKILL_SKL-074'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-088'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-088'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-088'}), (b {id: 'SKILL_SKL-074'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-089'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-089'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-089'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-090'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-090'}), (b {id: 'SKILL_SKL-081'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-090'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-090'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-091'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-091'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-091'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-092'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-092'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-092'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-093'}), (b {id: 'SKILL_SKL-087'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-093'}), (b {id: 'SKILL_SKL-078'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-093'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-093'}), (b {id: 'SKILL_SKL-086'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-094'}), (b {id: 'SKILL_SKL-077'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-094'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-094'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-094'}), (b {id: 'SKILL_SKL-080'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-095'}), (b {id: 'SKILL_SKL-036'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-095'}), (b {id: 'SKILL_SKL-039'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-095'}), (b {id: 'SKILL_SKL-040'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-095'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-095'}), (b {id: 'SKILL_SKL-043'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-095'}), (b {id: 'SKILL_SKL-041'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-095'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-096'}), (b {id: 'SKILL_SKL-118'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-096'}), (b {id: 'SKILL_SKL-100'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-096'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-096'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'ROLE_ROL-096'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'COURSE_CRS-001'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-001'}), (b {id: 'COURSE_CRS-011'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-001'}), (b {id: 'COURSE_CRS-012'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-002'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-002'}), (b {id: 'SKILL_SKL-010'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-002'}), (b {id: 'COURSE_CRS-010'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-003'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-003'}), (b {id: 'SKILL_SKL-015'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-003'}), (b {id: 'COURSE_CRS-005'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-003'}), (b {id: 'COURSE_CRS-006'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-003'}), (b {id: 'COURSE_CRS-007'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-004'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-004'}), (b {id: 'SKILL_SKL-062'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-004'}), (b {id: 'COURSE_CRS-011'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-004'}), (b {id: 'COURSE_CRS-012'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-005'}), (b {id: 'SKILL_SKL-100'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-005'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-005'}), (b {id: 'COURSE_CRS-006'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-005'}), (b {id: 'COURSE_CRS-016'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-006'}), (b {id: 'SKILL_SKL-036'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-006'}), (b {id: 'COURSE_CRS-008'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-006'}), (b {id: 'COURSE_CRS-009'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-006'}), (b {id: 'COURSE_CRS-017'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-007'}), (b {id: 'SKILL_SKL-039'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-007'}), (b {id: 'SKILL_SKL-046'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-007'}), (b {id: 'COURSE_CRS-008'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-007'}), (b {id: 'COURSE_CRS-009'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-007'}), (b {id: 'COURSE_CRS-015'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-008'}), (b {id: 'SKILL_SKL-040'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-009'}), (b {id: 'SKILL_SKL-041'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-009'}), (b {id: 'SKILL_SKL-043'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-010'}), (b {id: 'SKILL_SKL-018'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-010'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-011'}), (b {id: 'SKILL_SKL-114'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-011'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-011'}), (b {id: 'SKILL_SKL-046'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-011'}), (b {id: 'COURSE_CRS-017'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-012'}), (b {id: 'SKILL_SKL-055'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-012'}), (b {id: 'SKILL_SKL-056'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-012'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-012'}), (b {id: 'COURSE_CRS-013'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-013'}), (b {id: 'SKILL_SKL-048'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-013'}), (b {id: 'SKILL_SKL-052'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-013'}), (b {id: 'COURSE_CRS-014'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-013'}), (b {id: 'COURSE_CRS-015'}) MERGE (a)-[:PREREQUISITE_FOR]->(b);
MATCH (a {id: 'COURSE_CRS-014'}), (b {id: 'SKILL_SKL-049'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-014'}), (b {id: 'SKILL_SKL-117'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-014'}), (b {id: 'SKILL_SKL-051'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-015'}), (b {id: 'SKILL_SKL-048'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-015'}), (b {id: 'SKILL_SKL-039'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-016'}), (b {id: 'SKILL_SKL-118'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-016'}), (b {id: 'SKILL_SKL-100'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-017'}), (b {id: 'SKILL_SKL-119'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-017'}), (b {id: 'SKILL_SKL-046'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-018'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-018'}), (b {id: 'SKILL_SKL-074'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-018'}), (b {id: 'SKILL_SKL-107'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'COURSE_CRS-018'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:TEACHES]->(b);
MATCH (a {id: 'EMP_EMP-001'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-001'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-001'}), (b {id: 'SKILL_SKL-116'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-001'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-001'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-001'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-001'}), (b {id: 'ROLE_ROL-095'}) MERGE (a)-[:TARGETS_ROLE]->(b);
MATCH (a {id: 'EMP_EMP-002'}), (b {id: 'SKILL_SKL-003'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-002'}), (b {id: 'SKILL_SKL-010'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-002'}), (b {id: 'SKILL_SKL-018'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-002'}), (b {id: 'SKILL_SKL-017'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-002'}), (b {id: 'SKILL_SKL-116'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-002'}), (b {id: 'ROLE_ROL-002'}) MERGE (a)-[:TARGETS_ROLE]->(b);
MATCH (a {id: 'EMP_EMP-003'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-003'}), (b {id: 'SKILL_SKL-057'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-003'}), (b {id: 'SKILL_SKL-055'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-003'}), (b {id: 'SKILL_SKL-053'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-003'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-003'}), (b {id: 'ROLE_ROL-007'}) MERGE (a)-[:TARGETS_ROLE]->(b);
MATCH (a {id: 'EMP_EMP-004'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-004'}), (b {id: 'SKILL_SKL-114'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-004'}), (b {id: 'SKILL_SKL-062'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-004'}), (b {id: 'SKILL_SKL-039'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-004'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-004'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-004'}), (b {id: 'ROLE_ROL-005'}) MERGE (a)-[:TARGETS_ROLE]->(b);
MATCH (a {id: 'EMP_EMP-005'}), (b {id: 'SKILL_SKL-001'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-005'}), (b {id: 'SKILL_SKL-116'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-005'}), (b {id: 'SKILL_SKL-115'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-005'}), (b {id: 'SKILL_SKL-024'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-005'}), (b {id: 'SKILL_SKL-072'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-005'}), (b {id: 'ROLE_ROL-004'}) MERGE (a)-[:TARGETS_ROLE]->(b);
MATCH (a {id: 'EMP_EMP-006'}), (b {id: 'SKILL_SKL-070'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-006'}), (b {id: 'SKILL_SKL-071'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-006'}), (b {id: 'SKILL_SKL-107'}) MERGE (a)-[:HAS_SKILL]->(b);
MATCH (a {id: 'EMP_EMP-006'}), (b {id: 'SKILL_SKL-074'}) MERGE (a)-[:HAS_SKILL]->(b);